INSERT INTO TASKS(TASK_ID, TASK_NAME, TASK_DESC, TASK_STAT) VALUES(1, 'TASK 1', 'test5desc', TRUE);
INSERT INTO TASKS(TASK_ID, TASK_NAME, TASK_DESC, TASK_STAT) VALUES(2, 'TASK 2', 'test7desc', FALSE);